name = "app"
target = "javascript"
version = "0.1.0"
licenses = ["Apache-2.0"]
dev-dependencies = { lustre_dev_tools = ">= 1.8.2 and < 2.0.0" }

[dependencies]
gleam_stdlib = "~> 0.32"
modem = ">= 2.0.1 and < 3.0.0"
lustre = ">= 5.1.1 and < 6.0.0"
lustre_http = ">= 1.0.0"
